services:
  - type: web
    name: interview-backend
    runtime: python
    buildCommand: |
      pip install -r backend/app/requirements.txt
    startCommand: |
      python backend/app/main.py
    envVars:
      - key: ALLOWED_ORIGINS
        value: "https://"
